### ISSUE TITLE
Deploying environments with different configurations

### ISSUE THREAD

**Issue by tylr** [LevelbossMike/ember-deploy#21]
We deploy several environments for our app. They are configured within `config/environment.js`.

Currently the ember-deploy script is explicit about building the application with the production environment.

See: https://github.com/LevelbossMike/ember-deploy/blob/master/lib/commands/deploy.js#L22

This has the side-effect of not respecting all the env vars that my application needs to be aware of for each environment. e.g. apiHost, websocketHost, googleAnalyticsId, etc.

I considered adding these configurations to the deploy.json, but it seems a little out of the scope of that files purpose, or require a refactor that ends up conflating my application configuration with the deploy process.

Thoughts?

**Comment by LevelbossMike** [comment]
Hi and thanks for opening this issue!

Good catch and a useful feature request. It would be pretty easy to refactor this so that

`ember deploy --environment staging`

will build the application by passing the `staging` environment instead of `production` hard-coded. Most likely every environment except of development should be respected in the command. Building and uploading a development build does not seem very useful to me but it might be to some people.

Are you interested in sending a PR for this? I will have time to do this on the weekend probably but if you need this right now it's pretty easy to implement.

Until now I built the app with the respective environment myself and then used the `ember deploy:index` and `ember deploy:assets` tasks manually to upload necessary files. But including this in `ember-deploy` directly seems like a much more cleaner solution.

**Comment by tylr** [comment]
Great, that provides the clarity I needed. I've already got something working. I'll clean it up, fork and make a PR before the weekend.

We're migrating the bustle.com CMS to the ember-cli, deployment is the last step. :)

**Comment by LevelbossMike** [comment]
Bustle.com? Nice! Let me know if I can be of any more help if you run into problems.

**Comment by tylr** [comment]
Closing after agreeing on an approach in #23
